apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-stable
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git-codecommit.us-east-1.amazonaws.com/v1/repos/ops
    targetRevision: HEAD
    path: ./manifests/overlays/stable
  destination:
    server: https://kubernetes.default.svc
    namespace: default