apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherv1
spec:
  template:
    spec:
      containers:
      - name: weatherv1
        image: 531477552916.dkr.ecr.us-east-1.amazonaws.com/weatherv1:13
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
